{
  "formatVersion": "1.1",
  "component": {
    "group": "fman.ge.smart_auth",
    "module": "smart_auth_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_release-1.0.aar",
          "url": "smart_auth_release-1.0.aar",
          "size": 37373,
          "sha512": "12070a37b20491d8a9785fc1ba8b3256042e265eecc46b028e0aea556a9b29c2dac9457b86633ad5731a6a8944f84eb64e7cc57a0f93dbfb3a759acdff568a14",
          "sha256": "84e7183f4116ea731e232425e7001cf9c46402038dc1cc9165b5d5ba9774abb9",
          "sha1": "5751c93ac95f9f389eda15140c5feed46fcaac28",
          "md5": "f276d9cd3a31668b5635cee901fd5583"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_release-1.0.aar",
          "url": "smart_auth_release-1.0.aar",
          "size": 37373,
          "sha512": "12070a37b20491d8a9785fc1ba8b3256042e265eecc46b028e0aea556a9b29c2dac9457b86633ad5731a6a8944f84eb64e7cc57a0f93dbfb3a759acdff568a14",
          "sha256": "84e7183f4116ea731e232425e7001cf9c46402038dc1cc9165b5d5ba9774abb9",
          "sha1": "5751c93ac95f9f389eda15140c5feed46fcaac28",
          "md5": "f276d9cd3a31668b5635cee901fd5583"
        }
      ]
    }
  ]
}
