{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 22899,
          "sha512": "cd053294d045e0e5f312bf26adbdcca0619f109f6f9b2d57a9d3fb25a513fae7ec305b7c12cd8a0c5457e1496aa3799ada61fe75700d231f27555b656332ab05",
          "sha256": "d6c7cd56d2437316e06d6bc2e5794832a86a013f745f1051d0d532229568490d",
          "sha1": "f60dd9209d1ef06895ba35b991bf57ec4b59ffa0",
          "md5": "89a81af638ce2354a45c462b274da243"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_debug-1.0.aar",
          "url": "share_plus_debug-1.0.aar",
          "size": 22899,
          "sha512": "cd053294d045e0e5f312bf26adbdcca0619f109f6f9b2d57a9d3fb25a513fae7ec305b7c12cd8a0c5457e1496aa3799ada61fe75700d231f27555b656332ab05",
          "sha256": "d6c7cd56d2437316e06d6bc2e5794832a86a013f745f1051d0d532229568490d",
          "sha1": "f60dd9209d1ef06895ba35b991bf57ec4b59ffa0",
          "md5": "89a81af638ce2354a45c462b274da243"
        }
      ]
    }
  ]
}
